### ISSUE TITLE
Brazilian Portuguese (pt-BR) version

### ISSUE THREAD

**Issue by danielfireman** [dgryski/go-perfbook#17]
I am starting to work on the Brazilian Portuguese version.

Would you prefer taking a PR when the first sections are done or only when the whole document is completed?

**Comment by dgryski** [comment]
Either is fine.

**Comment by vitordagamagodoy** [comment]
@danielfireman I'll translate How to Optimize > Optimization Workflow later today

**Comment by danielfireman** [comment]
@vitordagamagodoy I am doing the 'Data Changes' today (so you finish up the section 2).

**Comment by dialmformart** [comment]
Hi @danielfireman , how we can setup this?

**Comment by dialmformart** [comment]
Can we close this issue?

**Comment by dgryski** [comment]
If you're happy with the state of the translation, you can close this. We can handle other fixes and PRs as they come up.

**Comment by danielfireman** [comment]
SGTM
