### ISSUE TITLE
Divide the parts of the book in 3 sections

### ISSUE THREAD

**Issue by phamtai97** [dgryski/go-perfbook#51]
Hi all.
I see the paragraph:
> This book is split into different sections:
   - Basic tips for writing not-slow software
      - CS 101-level stuff
   - Tips for writing fast software
     - Go-specific sections on how to get the best from Go
  - Advanced tips for writing really fast software
    - For when your optimized code isn't fast enough

But, I do not know how to divide the parts of the book in 3 sections above.

**Comment by dgryski** [comment]
I'm not sure I ever intended to actually divide up the content, but rather give an indication of the three types of optimizations that would be discussed.
