### ISSUE TITLE
zero only part of an array, rather than the whole thing

### ISSUE THREAD

**Issue by doggy8088** [dgryski/go-perfbook#60]
This sentence `zero only part of an array, rather than the whole thing` is really hard to understand for me. Can you describe more or change another way to say it?

I know what `"pay only for what you use, not what you could have used"` mean. Just don't get it what the "zero" means. It's a verb or noun?

**Comment by smlx** [comment]
In this context, "zero" is a verb taking the second definition [here](https://en.wiktionary.org/wiki/zero#Verb).

> (transitive, computing) To change a memory location or range to values of zero; to set a variable in a computer program to zero.
